flags: {}
packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: b71bcfa4701e129b69776e6951fe0bb7c8b26ea3
  extra-dep: true
extra-deps:
- murmur3-1.0.0
- pbkdf-1.1.1.1
- RFC1751-0.3.0.1
resolver: lts-3.4
